spring:
   application:
     name: service-one
  datasource:
   driverClassName: org.h2.Driver
   password: password
   url: jdbc:h2:file:/data/demo1
   username: sa
 
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
     defer-datasource-initialization: true
     hibernate:
       ddl-auto: update
     show-sql: true
